- name: Install developer tools on Ubuntu (Git, AWS CLI, eksctl, kubectl)
  hosts: all
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Git
      apt:
        name: git
        state: present

    - name: Install unzip and curl (required for AWS CLI and eksctl)
      apt:
        name:
          - unzip
          - curl
        state: present

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install

